### ISSUE TITLE
Create a common namespace for all PPB libraries and add Option library to that namespace

### ISSUE THREAD

**Issue by rustem-net** [PaddyPowerBetfair/Option#11]
Do you have any suggestions for the namespace name? 
I was thinking of PaddyPowerBetfair.Common.{library-name}.Option?

**Comment by rustem-net** [comment]
The problem is, both our Project(csproj) and Class(cs) names are Option. If we want to use the default namespace convention, as a good practice we should either change Project or Class name to prevent possible ugly code & intellisense errors for namespaces. 
I think it's easier to change the Project, to something like : **Maybe**. 

`using PaddyPowerBetfair.Common.Maybe;`

`var option = Option.Some(5);`

instead of

`using PaddyPowerBetfair.Common;`

`var option = Option.Option.Some(5);`

**Comment by sandorbari** [comment]
What if we just call it Library? PaddyPowerBetfair.Common.Library.Option
This is my best idea, I'm sorry. I'm ok with Maybe too btw.

**Comment by rustem-net** [comment]
Fixed by PR #18
