### ISSUE TITLE
Remove MSTest and use xunit

### ISSUE THREAD

**Issue by cosie90** [PaddyPowerBetfair/Option#2]
Remove MSTest and replace with xunit

**Comment by cosie90** [comment]
Part of this we should use Roy Osherove convention for test naming.
ie: UnitOfWork_StateUnderTest_ExpectedBehavior
http://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html

**Comment by sandorbari** [comment]
It's done, MSTest is replaced with xUnit. Changes merged to master.
