### ISSUE TITLE
Create CI to build and run tests

### ISSUE THREAD

**Issue by cosie90** [PaddyPowerBetfair/Option#3]
Create CI (suggested using Travis) to build and run the tests

**Comment by sandorbari** [comment]
Travis CI is integrated with the master branch. 
Regarding PRs, there are 2 checks in place:
 - When a PR is raised, it will build it against the master branch and run the tests. PR can be merged only when it passes the build.
 - When a request is raised to merge a branch existing in the PaddyPowerBetfair/Option repository to the master branch - so we won't try to merge a PR raised from a fork - it will build the branch and run the tests against that branch.

Every merge/push to the master branch triggers a build as well.
