### ISSUE TITLE
Create a fantastic, first-class README.md which is important for new visitors.

### ISSUE THREAD

**Issue by cosie90** [PaddyPowerBetfair/Option#6]

**Comment by rodoherty1** [comment]
It would be great to see a landing page which explains 
* the purpose of this library
* how to use it in your project (i.e. is there a downloadable binary or does it have to be compiled)
* a clear set of tests or examples that show how this library can be used in practice.

**Comment by rustem-net** [comment]
Included the purpose of Option library in README.md as well as basic examples and the benefits of using Option library instead of nested if statements. Changes merged to master.
